absolutePanel(id = "controls", 
              class = "panel panel-default", 
              fixed = TRUE,
              draggable = TRUE, 
              top = "20%", left = "auto", right = 370, bottom = "auto",
              width = 400, 
              p(""),
              selectInput(inputId = "selectPointInfo",
                          label=NULL,
                          choices = NULL,
                          selected=NULL,
                          multiple = FALSE),
              bsCollapse(id = "collapseExample1", open = "Location properties",
                         bsCollapsePanel("Location properties",
                                         #h5("Click on the Marker on the Map: "),
                                         tableOutput('point_table'),
                                         # h5("ID: ",textOutput(outputId = "pr1", inline = TRUE)),
                                         # h5("Soil texture: ", textOutput(outputId = "pr2", inline = TRUE)),
                                         # h5("Upper depth [cm]: ", textOutput(outputId = "pr3", inline = TRUE)),
                                         # h5("Lower depth [cm]: ", textOutput(outputId = "pr4", inline = TRUE)),
                                         # h5("Address: ", textOutput(outputId = "pr5", inline = TRUE)),
                                         style = "success"),
                         bsCollapsePanel("VISNIR spectra profile",
                                         h5("VISNIR spectra profile: "), 
                                         plotlyOutput("pl.vis"), 
                                         style = "success"),
                         bsCollapsePanel("MIR spectra profile",
                                         h5("MIR spectra profile: "), 
                                         plotlyOutput("pl.mir"), 
                                         style = "success")
              ) # bsCollapse
)  #absolutePanel Point Info